"use client";

import { FormEvent, useMemo, useState } from "react";
import type { Partner } from "@/lib/types";

const trackingUrl = (slug: string) => `${process.env.NEXT_PUBLIC_TRACKING_BASE_URL || "https://yourwebsite.com"}/?utm_source=${encodeURIComponent(slug)}&utm_medium=referral`;

export function PartnerDashboard({ initialPartners, configured }: { initialPartners: Partner[]; configured: boolean }) {
  const [partners, setPartners] = useState(initialPartners), [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  const [form, setForm] = useState({ name: "", website: "", slug: "" });
  const createdUrl = useMemo(() => form.slug ? trackingUrl(form.slug) : "", [form.slug]);
  async function submit(event: FormEvent) {
    event.preventDefault(); setBusy(true); setMessage("");
    const response = await fetch("/api/partners", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) });
    const payload = await response.json(); setBusy(false);
    if (!response.ok) return setMessage(payload.error || "Could not create partner.");
    setPartners((items) => [payload.partner, ...items]); setMessage("Partner created. Your tracking link is ready to copy.");
  }
  return <>
    <div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-emerald-700">PARTNER MANAGEMENT</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Partners</h1><p className="mt-2 text-slate-500">Create referral links and see the leads each partner drives.</p></div><button onClick={() => { setOpen(true); setMessage(""); }} className="rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-emerald-700">+ Add partner</button></div>
    {!configured && <div className="mb-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Demo mode:</b> Add Supabase environment variables to persist partners and leads. Setup instructions are in the README.</div>}
    <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold">Your partner directory</h2><p className="mt-1 text-sm text-slate-500">Tracking URLs use each partner’s unique UTM source.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Partner</th><th className="px-5 py-3">Slug</th><th className="px-5 py-3">Website</th><th className="px-5 py-3">Tracking link</th></tr></thead><tbody>{partners.length ? partners.map((p) => <tr key={p.id} className="border-t border-slate-100"><td className="px-5 py-4 font-semibold">{p.name}</td><td className="px-5 py-4"><code className="rounded bg-emerald-50 px-2 py-1 text-emerald-800">{p.slug}</code></td><td className="px-5 py-4 text-slate-500">{p.website}</td><td className="px-5 py-4"><button onClick={() => navigator.clipboard.writeText(trackingUrl(p.slug))} className="font-medium text-emerald-700 hover:underline">Copy link</button></td></tr>) : <tr><td colSpan={4} className="px-5 py-12 text-center text-slate-500">No partners yet. Add your first referral partner.</td></tr>}</tbody></table></div></section>
    {open && <div className="fixed inset-0 z-10 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-bold">Add a partner</h2><p className="mt-1 text-sm text-slate-500">A UTM referral link is generated from the slug.</p></div><button type="button" onClick={() => setOpen(false)} className="text-xl text-slate-400">×</button></div><div className="mt-5 grid gap-4"><label className="text-sm font-medium">Partner name<input required value={form.name} onChange={e => setForm({...form, name:e.target.value})} className="mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2" placeholder="Acme Media"/></label><label className="text-sm font-medium">Website<input required type="url" value={form.website} onChange={e => setForm({...form, website:e.target.value})} className="mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2" placeholder="https://acme.example"/></label><label className="text-sm font-medium">UTM slug<input required pattern="[a-z0-9_-]+" value={form.slug} onChange={e => setForm({...form, slug:e.target.value.toLowerCase()})} className="mt-1 block w-full rounded-lg border border-slate-300 px-3 py-2" placeholder="acme_media"/><span className="mt-1 block text-xs text-slate-500">Lowercase letters, numbers, hyphens, and underscores only.</span></label>{createdUrl && <div className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-900"><b>Tracking link</b><div className="mt-1 break-all font-mono text-xs">{createdUrl}</div></div>}{message && <p className="text-sm text-emerald-700">{message}</p>}<button disabled={busy} className="rounded-lg bg-emerald-600 px-4 py-2.5 font-semibold text-white disabled:opacity-50">{busy ? "Creating…" : "Create partner"}</button></div></form></div>}
  </>;
}
