import { LayoutShell } from "@/components/layout-shell";
import { createSupabaseServerClient, isSupabaseConfigured } from "@/lib/supabase";
import type { Lead } from "@/lib/types";

export default async function LeadsPage() {
  let leads: Lead[] = []; const configured = isSupabaseConfigured();
  if (configured) { const { data } = await createSupabaseServerClient().from("leads").select("*").order("created_at", { ascending: false }); leads = data || []; }
  return <LayoutShell><div className="mb-8"><p className="text-sm font-semibold text-emerald-700">CONVERSION ATTRIBUTION</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Leads</h1><p className="mt-2 text-slate-500">Every submitted lead is connected to its referring partner.</p></div>{!configured && <div className="mb-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><b>Demo mode:</b> Connect Supabase to display submitted leads.</div>}<section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 px-5 py-4"><h2 className="font-semibold">Attributed submissions</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Lead</th><th className="px-5 py-3">Email</th><th className="px-5 py-3">Partner</th><th className="px-5 py-3">Submitted</th></tr></thead><tbody>{leads.length ? leads.map(lead => <tr key={lead.id} className="border-t border-slate-100"><td className="px-5 py-4 font-semibold">{lead.lead_name}</td><td className="px-5 py-4 text-slate-600">{lead.lead_email}</td><td className="px-5 py-4"><code className="rounded bg-emerald-50 px-2 py-1 text-emerald-800">{lead.partner_slug}</code></td><td className="px-5 py-4 text-slate-500">{new Date(lead.created_at).toLocaleString()}</td></tr>) : <tr><td colSpan={4} className="px-5 py-12 text-center text-slate-500">No attributed leads yet.</td></tr>}</tbody></table></div></section></LayoutShell>;
}
